<?php

namespace LBM\UserBundle\Repository;

/**
 * LbmRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
