# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    LBM\UserBundle\Entity\LbmUser: plaintext

  role_hierarchy:
    ROLE_USER:        [ROLE_USER]
    ROLE_MANAGER:     [ROLE_USER]
    ROLE_ADMIN:       [ROLE_MANAGER, ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MANAGER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    LBM\UserBundle\Entity\LbmUser
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main_login:
      pattern:   ^/login$
      anonymous: true

    main:
      pattern:   ^/
      anonymous: false
      provider:  main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: dashboard

      logout:
        path:  logout
        target: /

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
