# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

   app.twig_extension:
        class: LBM\ExtensionBundle\TwigExtension\UserFriendly
        public: false
        tags:
            - { name: twig.extension }

#   custorm_url_generator:
#        class: LBM\UserBundle\Form\UserType
#        arguments: [@router]