<?php

namespace LBM\ReferencielBundle\Repository;

/**
 * LbmDetailRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmDetailRefRepository extends \Doctrine\ORM\EntityRepository
{
}
