<?php

namespace LBM\ReferencielBundle\Repository;

/**
 * LbmGlobalRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmGlobalRefRepository extends \Doctrine\ORM\EntityRepository
{
}
