<?php

namespace LBM\ContactBundle\Repository;

/**
 * LbmAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
