<?php

namespace LBM\ContactBundle\Repository;

/**
 * LbmCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
