<?php

namespace LBM\ContactBundle\Repository;

/**
 * LbmCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCityRepository extends \Doctrine\ORM\EntityRepository
{
}
