<?php

namespace LBM\ContactBundle\Repository;

/**
 * LbmEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
