<?php

namespace LBM\ContactBundle\Repository;

/**
 * LbmTelephonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmTelephonRepository extends \Doctrine\ORM\EntityRepository
{
}
