<?php

namespace LBM\OrganizationBundle\Repository;

/**
 * LbmApeCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmApeCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
