<?php

namespace LBM\OrganizationBundle\Repository;

/**
 * LbmBusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmBusinessUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
