<?php

namespace LBM\OrganizationBundle\Repository;

/**
 * LbmBusinessEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmBusinessEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
