<?php

namespace LBM\OrganizationBundle\Repository;

/**
 * LbmCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
