<?php

namespace LBM\OrganizationBundle\Repository;

/**
 * LbmLegalCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmLegalCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
